repos:
-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        args: [--config=setup.cfg]
-   repo: local
    hooks:
    -   id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        args: [-sp=setup.cfg]
-   repo: local
    hooks:
    -   id: pydocstyle
        name: pydocstyle
        entry: pydocstyle
        language: system
        types: [python]
        exclude: /tests/
        args: [--config=setup.cfg]
